// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { inject } from 'vue';
import { AppContextKey } from 'D:/project/vue-pro/node_modules/.pnpm/@umijs+renderer-vue@4.0.8_m4vbylfoxvsy5tjrj5sjio42gm/node_modules/@umijs/renderer-vue';

export function useAppData() {
  const state = inject(AppContextKey);
  if (!state) {
    throw new Error('AppContext is no provide');
  }

  return state;
}
