// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { defineComponent } from 'vue';

export default defineComponent({
  setup() {
    return () => <router-view></router-view>;
  },
});
