// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { createWebHashHistory, createMemoryHistory, createWebHistory } from 'D:/project/vue-pro/node_modules/.pnpm/@umijs+renderer-vue@4.0.8_m4vbylfoxvsy5tjrj5sjio42gm/node_modules/@umijs/renderer-vue';
import type { RouterHistory } from 'D:/project/vue-pro/node_modules/.pnpm/@umijs+renderer-vue@4.0.8_m4vbylfoxvsy5tjrj5sjio42gm/node_modules/@umijs/renderer-vue';

let history: RouterHistory;
export function createHistory(opts: any) {
  if (opts.type === 'hash') {
    history = createWebHashHistory(opts.basename);
  } else if (opts.type === 'memory') {
    history = createMemoryHistory(opts.basename);
  } else {
    history = createWebHistory(opts.basename);
  }
  return history;
}

export { history };
