// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createMemoryHistory, createRouter, createWebHashHistory, createWebHistory, onBeforeRouteLeave, onBeforeRouteUpdate, RouterLink, RouterView, useLink, useRoute, useRouter, AppContextKey, renderClient } from 'D:/project/vue-pro/node_modules/.pnpm/@umijs+renderer-vue@4.0.8_m4vbylfoxvsy5tjrj5sjio42gm/node_modules/@umijs/renderer-vue';
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/project/vue-pro/node_modules/.pnpm/umi@4.0.8_typescript@4.7.4/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// plugins
export { useAppData } from 'D:/project/vue-pro/src/.umi/plugin-vue';
// plugins types.d.ts
